### ISSUE TITLE
Remarques

### ISSUE THREAD

**Issue by AlbanMinassian** [davidB/ffizer#28]
Ffizer est très sympathique (et largement meilleur que cargo-generate).
Merci pour cet excellent programme.

Voici mes remarques de "première fois": 

- j'ai tout de suite envie de taper ``ffizer --source ./xxxx --destination .`` (99% des utilisateurs aussi feignant que moi ont envie de faire). Mais il faut en réalité taper ``ffizer apply --source ./xxxx --destination .`` Donc on se demande a quoi sert la commande ``ffizer`` tout seul car c'est quand même la première commande expliqué dans le README.md.

- ``--source-folder`` et ``--source`` sont ambiguës car j'ai lu la doc en diagonal et j'ai d'abord tapé ``ffizer --source-folder ./xxxx --destination .`` ... peut être renommer ``source-folder`` en ``subfolder`` et n'avoir que un seul paramètre ``--source``.

- ``ffizer upgrade`` ne nécessite peut être pas de subcommand mais seulement ``ffizer --upgrade``.

Cordialement
Alban

**Comment by davidB** [comment]
Bonjour,

`ffizer --source ./xxxx --destination .` etait la commande avant 0.9.0 (il y a moins de 10j). Le changement est du a l'introduction `upgrate`. Le choix d'utiliser des sub commandes ajoute de la lourdeur pour 99% des usages. Mais il permet de maintenir une coherence dans l'api cli entre ce qui est optionel et obligatoire suivant les cas d'utilisation. C'est plus simple a documenter et expliquer (et a coder), que l'ajout d'un flag ``--upgrade` . eg:
- upgrade et apply sont exclusif
- upgrade ne necessite pas --source, --destination,...
- `--destination` et `--source`sont obligatoire pour `apply`

Donc je suis d'accord avec ton point de vue, je me suis fait les memes remarques avant de basculer sur des subcommandes, et j'espere que cela ne sera pas un trop mauvais choix pour le future (et les utilisateurs).

Merci.

PS: L'ajout de sub commandes me permettra aussi d'ajouter a ffizer d'autre sub commandes (eg: listes les templates, checker un template, ???) sans impacter/casser la commande principale.

PS 2: `source-folder` sera renommer `source-subfolder` dans la prochaine version.

**Comment by AlbanMinassian** [comment]
ok
